# Remove obsolete version field

services:
  db:
    image: postgres:15-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../infra/docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ../../services/api
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener

  worker:
    build: ../../services/worker
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener

  data_ingest:
    build: ../../services/data_ingest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener
      IEX_CLOUD_API_KEY: ${IEX_CLOUD_API_KEY}
      DATA_API_BASE_URL: https://cloud.iexapis.com/stable
    restart: unless-stopped
    labels:
      - "com.docker.compose.schedule=*/30 * * * * *"

  notifier:
    build: ../../services/notifier
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      FROM_EMAIL: ${FROM_EMAIL}

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

networks:
  default:
    name: options_screener_network

volumes:
  pgdata: 