version: "3.9"

services:
  db:
    image: flyio/postgres-flex:15
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../infra/docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  api:
    build: ../../services/api
    depends_on: [db]
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener

  worker:
    build: ../../services/worker
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener

  data_ingest:
    build: ../../services/data_ingest
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener
      DATA_API_KEY: ${DATA_API_KEY}
      DATA_API_BASE_URL: https://cloud.iexapis.com/stable
    restart: unless-stopped
    labels:
      - "com.docker.compose.schedule=*/30 * * * * *"

  notifier:
    build: ../../services/notifier
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://postgres:changeme@db:5432/opt_screener
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      FROM_EMAIL: ${FROM_EMAIL}

volumes:
  pgdata: 