name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build images
        run: docker compose -f infra/docker/docker-compose.yaml build
      - name: Unit tests placeholder
        run: echo "no tests yet"
      - name: Run data-ingest tests
        run: |
          cd services/data_ingest
          pip install -r requirements.txt
          pytest -q 