name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build images
        run: docker compose -f infra/docker/docker-compose.yaml build
      - name: Install dependencies
        run: |
          pip install pytest httpx
          pip install -r services/api/requirements.txt
          pip install -r services/worker/requirements.txt
      - name: Run unit tests
        run: python -m pytest tests/
      - name: Run services in background to test
        run: |
          docker compose -f infra/docker/docker-compose.yaml up --build -d

      - name: Wait for services to be healthy
        run: sleep 15 # Give services time to start

      - name: ✅ Get evidence for Done Check 1
        run: |
          echo "--- Testing API endpoint ---"
          curl -X POST http://localhost:8000/screen -H "Content-Type: application/json" -d '{"tickers": ["AAPL", "TSLA"], "strategy": "covered_call"}'
          echo "" # new line

      - name: ✅ Get evidence for Done Check 2
        run: |
          echo "--- Checking Worker logs ---"
          docker compose -f infra/docker/docker-compose.yaml logs worker
      - name: Run data-ingest tests
        run: |
          cd services/data_ingest
          pip install -r requirements.txt
          pytest -q 